# Copyright 2021 VMware
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartographer-example-registry-creds-sa
#@ if data.values.registry.password != "":
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
#@ end
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kapp-permissions
rules:
- apiGroups:
  - serving.knative.dev
  resources: ['services']
  verbs: ['*']
- apiGroups: [""]
  resources: ['configmaps']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kapp-permissions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kapp-permissions
subjects:
  - kind: ServiceAccount
    name: cartographer-example-registry-creds-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kpack.io
      - kapp.k14s.io/v1alpha1
      - kappctrl.k14s.io
      - serving.knative.dev/v1
      - carto.run
    resources:
      - gitrepositories
      - images
      - configs
      - apps
      - services
      - runnables
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-config-creation-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-creation-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-creation-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-git-writing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-writing-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account_name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-writing-role
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch