---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: kustomize-deployment
spec:
  template:
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
    kind: Kustomization
    metadata:
      name: $(deliverable.metadata.name)$
    spec:
      sourceRef:
        kind: GitRepository
        name: $(deliverable.metadata.name)$
      path: "./packageinstalls/$(deliverable.metadata.name)$"
      interval: 60m
      timeout: 5m
      prune: true
      wait: true
      force: true